[package]
name = "cbnf-ls"
version = "0.0.1"
edition = "2021"

[dependencies]
# server
tower-lsp = "0.20"
tokio = { version = "1.40", features = ["full"] }
# cbnf
cbnf = { path = "../cbnf/" }

[lints]
workspace = true
